name: Integration Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "${{secrets.DB_PASSWORD}}"
          MYSQL_DATABASE: "${{secrets.DATABASE}}"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        env:
          HOST: 127.0.0.1
          DB_USERNAME: "${{secrets.DB_USERNAME}}"
          DB_PASSWORD: "${{secrets.DB_PASSWORD}}"
          DATABASE: "${{secrets.DATABASE}}"
        run: npm run integration-test