name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start

      - name: Wait for MySQL to start
        run: |
          while ! mysqladmin ping -h127.0.0.1 --silent; do
            sleep 1
          done

      - name: Set up MySQL database
        run: |
          mysql -h127.0.0.1 -uroot -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATABASE_NAME }};"
          mysql -h127.0.0.1 -uroot -e "GRANT ALL PRIVILEGES ON ${{ secrets.DATABASE_NAME }}.* TO '${{ secrets.DATABASE_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DATABASE_PASSWORD }}';"

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        env:
          HOST: 127.0.0.1
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: npm run integration-test
