name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]  # Adjust the node version based on your application requirements

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "2108786Z@kir"
          MYSQL_DATABASE: "CloudComputing"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=3s --health-retries=2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Wait for Database
        run: npm run wait-for-db

      - name: Run integration tests
        env:
          HOST: 127.0.0.1
          DB_USERNAME: "root"
          DB_PASSWORD: "2108786Z@kir"
          DATABASE: "CloudComputing"
        run: npm run integration-test
