name: Integration Tests with MySQL

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 2108786Z@kir
          MYSQL_DATABASE: CloudComputing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p2108786Z@kir"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Integration Tests
      run: npm run integration-test
      env:
        NODE_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: 2108786Z@kir
        DB_NAME: CloudComputing
