name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e "CREATE USER 'zakir'@'localhost' IDENTIFIED BY '2108786Z@kirmemon';"
          mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'zakir'@'localhost' WITH GRANT OPTION;"
          mysql -u root -proot -e "CREATE DATABASE cloud;"

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        env:
          HOST: 127.0.0.1
          DATABASE_USERNAME: zakir
          DATABASE_PASSWORD: 2108786Z@kirmemon
          DATABASE_NAME: cloud
        run: npm run integration-test

