name: Packer CI

on:
  pull_request:
    paths:
      - 'packer-template/**'  # Modify this path according to your template location

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip packer_1.7.4_linux_amd64.zip
        sudo mv packer /usr/local/bin/packer
        packer version

    - name: Packer fmt
      run: |
        cd packer-template
        packer fmt -check .
    
    - name: Packer validate
      run: |
        cd packer-template
        packer validate .
