name: Packer CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip application code
        run: |
         # Change directory to the root of the repository
         cd ..
         # Zip the entire repository
         zip -r backend/webapp.zip backend/*

      - name: Install Packer
        run: |
          curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer version

      - name: Packer fmt
        id: fmt
        run: |
          cd backend
          git_diff_before=$(git diff)
          packer fmt packer.pkr.hcl
          git_diff_after=$(git diff)

          if [ "$git_diff_before" != "$git_diff_after" ]; then
            echo "Packer fmt modified files. Please fix the formatting and commit the changes."
            echo "exit_code=1" >> $GITHUB_OUTPUT
          else
            echo "Packer fmt did not modify any files."
            echo "exit_code=0" >> $GITHUB_OUTPUT
          fi

      - name: Packer validate
        id: validate
        run: |
          cd backend
          packer validate packer.pkr.hcl
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

      - name: Check exit codes
        if: steps.fmt.outputs.exit_code != 0 || steps.validate.outputs.exit_code != 0
        run: |
          echo "Packer lint failed. Please fix the issues and try again."
          exit 1