name: Integration Tests, Image Creation

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Integration Test
        run: |
          ./packer-script.sh
        continue-on-error: true

  build-artifact:
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
          sudo bash nodesource_setup.sh
          sudo apt-get install -y nodejs

      - name: Install MySQL Server
        run: |
          sudo apt-get install -y mysql-server
          sudo systemctl enable mysql

      - name: Install Application Dependencies
        run: npm install

      - name: Create .env File
        run: echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}\nDATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}\nDATABASE_NAME=${{ secrets.DATABASE_NAME }}" > .env

  build-custom-image:
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: init for Custom Image with Packer
        run: |
          cd backend
          echo "init for Custom Image with Packer"
          packer init packer.pkr.hcl


      - name: Build Custom Image with Packer
        run: |
          cd backend
          echo "Building custom image with Packer"
          packer build packer.pkr.hcl
