name: VM CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Zip application code
        run: |
          # Change directory to the root of the repository
          cd .
          cd FORKEDREPO

          # Zip the entire repository
          zip -r webapp.zip .

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Environment File
        run: |
          cat << EOF > .env
          HOST: 127.0.0.1
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          EOF
        shell: bash 

      - name: Install Packer
        run: |
          curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer version

      - name: Initiate Packer template
        run: |
          cd backend
          packer init packer.pkr.hcl

      - name: Validate Packer template
        run: |
          cd backend
          packer validate packer.pkr.hcl

      - name: Build Packer template
        run: |
          cd backend
          packer build packer.pkr.hcl
