name: VM CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Zip application code
        run: |
          # Change directory to the root of the repository
          cd .

          # Zip the entire repository
          zip -r webapp.zip .

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install Packer
        run: |
          curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer version

      - name: Initiate Packer template
        run: |
          packer init packer.pkr.hcl

      - name: Validate Packer template
        run: |
          packer validate packer.pkr.hcl

      - name: Build Packer template
        run: |
          packer build packer.pkr.hcl

      - name: Create new instance template version
        run: |
          gcloud compute images list  --sort-by=~creationTimestamp --format='value(NAME)' --limit=1
          gcloud compute instance-templates create webapp-instance-template-version2 --project=cloudcomputing-demo-415406 --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=webapp --metadata=startup-script=\#\!/bin/bash$'\n'$'\n'set\ -e$'\n'echo\ \"Hello\ World\!\"$'\n'\ \ $'\n'$'\n'env_file=\"/home/webapp/.env\"$'\n'$'\n'echo\ \"DATABASE_NAME=webapp\"\ \>\>\ \"\$env_file\"$'\n'echo\ \"HOST=10.208.99.2\"\ \>\>\ \"\$env_file\"$'\n'echo\ \"DATABASE_USERNAME=webapp\"\ \>\>\ \"\$env_file\"$'\n'echo\ \"DATABASE_PASSWORD=C4ntkgtYZHEZz3vz\"\ \>\>\ \"\$env_file\"$'\n'echo\ \"PORT=3306\"\ \>\>\ \"\$env_file\"$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=cloud-computing-zakir@cloudcomputing-demo-415406.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/logging.write --region=us-east1 --tags=allow-health-check --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/cloudcomputing-demo-415406/global/images/custom-image-mysql,kms-key=projects/cloudcomputing-demo-415406/locations/us-east1/keyRings/rings-of-kms-eight/cryptoKeys/vm-crypto-key,mode=rw,size=20,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
  
      - name: Configure instance group with new template
        run: |
          gcloud compute instance-groups managed set-instance-template webapp-igm --region=us-east1 --template=webapp-instance-template-version4 --project=cloudcomputing-demo-415406
  
      - name: Start rolling update
        run: |
          gcloud compute instance-groups managed rolling-action start-update webapp-igm --version=template="webapp-instance-template-version4" --max-surge=5 --region=us-east1 --project=cloudcomputing-demo-415406
  
      - name: Monitor instance group update
        run: |
          status="RUNNING"
          while [ "$status" != "True" ]; do
            status=$(gcloud compute instance-groups managed describe webapp-igm --region=us-east1 --project=cloudcomputing-demo-415406 --format="value(status.versionTarget.isReached)")
            sleep 10
          done
